/* Generated by GOB (v2.0.14)   (do not edit directly) */

#include <glib.h>
#include <glib-object.h>
#ifndef __GTK_TEXT_COMPLETION_DATA_H__
#define __GTK_TEXT_COMPLETION_DATA_H__

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/*
 * Type checking and casting macros
 */
#define GTK_TYPE_TEXT_COMPLETION_DATA	(gtk_text_completion_data_get_type())
#define GTK_TEXT_COMPLETION_DATA(obj)	G_TYPE_CHECK_INSTANCE_CAST((obj), gtk_text_completion_data_get_type(), GtkTextCompletionData)
#define GTK_TEXT_COMPLETION_DATA_CONST(obj)	G_TYPE_CHECK_INSTANCE_CAST((obj), gtk_text_completion_data_get_type(), GtkTextCompletionData const)
#define GTK_TEXT_COMPLETION_DATA_CLASS(klass)	G_TYPE_CHECK_CLASS_CAST((klass), gtk_text_completion_data_get_type(), GtkTextCompletionDataClass)
#define GTK_IS_TEXT_COMPLETION_DATA(obj)	G_TYPE_CHECK_INSTANCE_TYPE((obj), gtk_text_completion_data_get_type ())

#define GTK_TEXT_COMPLETION_DATA_GET_CLASS(obj)	G_TYPE_INSTANCE_GET_CLASS((obj), gtk_text_completion_data_get_type(), GtkTextCompletionDataClass)

/* Private structure type */
typedef struct _GtkTextCompletionDataPrivate GtkTextCompletionDataPrivate;

/*
 * Main object structure
 */
#ifndef __TYPEDEF_GTK_TEXT_COMPLETION_DATA__
#define __TYPEDEF_GTK_TEXT_COMPLETION_DATA__
typedef struct _GtkTextCompletionData GtkTextCompletionData;
#endif
struct _GtkTextCompletionData {
	GObject __parent__;
	/*< private >*/
	GtkTextCompletionDataPrivate *_priv;
};

/*
 * Class definition
 */
typedef struct _GtkTextCompletionDataClass GtkTextCompletionDataClass;
struct _GtkTextCompletionDataClass {
	GObjectClass __parent__;
};


/*
 * Public methods
 */
GType	gtk_text_completion_data_get_type	(void);
const gchar * 	gtk_text_completion_data_get_name	(GtkTextCompletionData * self);
GdkPixbuf * 	gtk_text_completion_data_get_icon	(GtkTextCompletionData * self);
gpointer 	gtk_text_completion_data_get_user_data	(GtkTextCompletionData * self);
GtkTextCompletionData * 	gtk_text_completion_data_new_with_data	(const gchar * name,
					GdkPixbuf * icon,
					gpointer user_data);
void 	gtk_text_completion_data_free	(GtkTextCompletionData * data);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
